config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  devise_for :users

  get "show" => "users#show"

  resources :users do
      collection { get "search"}
    end

  resources :items
  root :to => 'top#index'
   get '/top' => 'top#home'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	mount_uploader :image, ImageUploader
	
	class << self
		def search(query)
			rel = order("id")
			if query.present?
				rel = rel.where("name LIKE ?","%#{query}")
			end
			rel
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:category, :name, :image, :count)
    end
end

app/controllers/top_controller.rb
# coding: utf-8

class TopController < ApplicationController
	def home
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users =User.all
	end

	def show
		@user = User.find(params[:id])
	end

	def search
		@users = User.search(params[:q])
		render "index"
	end

	def new
		@user = User.new(name:("農園太郎"))
	end

	def edit
		@user = User.find(params[:id])
	end
	def create
		params.permit!
		@user =User.new(params[:user])
		if @user.save
			redirect_to @user, notice: "会員登録しました。"
		else
			render "new"
		end
	end

	def update
		params.permit!
		@user = User.find(params[:id])
		@user.assign_attributes(params[:user])
		if @user.save
			redirect_to @user, notice: "会員情報を更新しました。"
		else
			render "edit"
		end
	end
	def destroy
		params.permit!
		@user =User.find(params[:id])
		@user.destroy
		redirect_to :users, notice: "会員を削除しました。"
	end

	def user_params
 		params.require(:user).permit(:name,:job,:description,:role,:image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Items</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Name</th>
      <th>Image</th>
      <th>Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.category %></td>
        <td><%= item.name %></td>
        <td><%= item.image %></td>
        <td><%= item.count %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @item.image %>
</p>

<p>
  <strong>Count:</strong>
  <%= @item.count %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Farmshare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<header>
  <nav>
    <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
    <% if user_signed_in? %>
      <!-- current_user は現在ログインしているUserオブジェクトを返すdeviseのHelperメソッド -->
      <!-- *_path はUserモデルを作成したときに、
        deviseにより自動で作成されてますので、rake routesで確認できます -->
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'プロフィール変更', edit_user_registration_path %> |
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "サインイン", new_user_registration_path %> |
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
  </nav>
</header>
</body>
</html>

app/views/top/index.html.erb
<h1>Farmshare</h1>
<p>農家と購買者のマッチングサービス!</p>
<p>aa</p>

<%= link_to '農産物を投稿するよ!', new_item_path %>


<%# @items.each do |item| %>
<%#= item.body %>
<%# end %>

app/views/users/_form.html.erb
<table>
  <tr>
    <th><%= form.label :name, "氏名" %></th>
    <td><%#= form.text_field :name %></td>
  </tr>
  <tr>
    <th><%= form.label :job, "職業" %></th>
    <td><%#= form.text_field :job %></td>
  </tr>
  <tr>
    <th><%= form.label :description, "紹介文" %></th>
    <td><%#= form.text_area :description, cols: 40, rows: 5 %></td>
  </tr>
  <tr>
    <th><%#= User.human_attribute_name("会員区分") %></th>
    <td>
      <%#= form.radio_button :role, 0 %>農家の方
      <%#= form.radio_button :role, 1 %>購入者の方
    </td>
  </tr>
  <tr>
    <th><%= form.label :image %></th>
    <td><%=# form.file_field :image %></td>
  </tr>
</table>

app/views/users/edit.html.erb
<% @page_title ="マイページの編集" %>

<h1><%= @page_title %></h1>

<p><%= link_to "マイページへ戻る", @user %></p>

<%= form_for @user do |form| %>
<%= render "form", form: form %>
<p><%= form.submit %></p>
<% end %>

app/views/users/index.html.erb
<% @page_title ="会員一覧" %>

<h1><%= @page_title %></h1>

<%= form_tag :search_users, method: :get do %>
	<p><%= text_field_tag "q", params[:q] %></p>
	<p><%= submit_tag "検索" %></p>
<% end %>
<p><%= link_to "会員の新規登録", :new_user %></p>
<% if @users.present? %>
<table>
  <tr>
    <th>氏名</th>
    <th>職業</th>
    <th>会員区分</th>
    <th>Image</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%#= link_to user.name, user %></td>
    <td><%#= user.job %></td>
    <td><%#= user.role %></td>
    <td><%#= image_tag user.image_url %></td>
    <td>
      <%= link_to "編集",  [:edit, user] %> |
      <%= link_to "削除", user, method: :delete,
            data: { confirm: "本当に削除しますか?" } %>
    </td>
  </tr>
  <% end %>
</table>
<% else %>
<p>会員情報がありません。</p>
<% end %>

app/views/users/new.html.erb
<% @page_title ="新規登録" %>

<h1><%= @page_title %></h1>

<%=form_for @user do |form| %>
<%= render "form", form: form %>
<p><%= form.submit%></p>
<% end %>

app/views/users/show.html.erb
<% @page_title = "マイページ" %>

<h1><%= @page_title %></h1>

<p><%= link_to "編集", [:edit, @user] %></p>
<p><%= link_to "戻る", users_path %></p>

<table>
	<tr>
		<th>氏名</th>
		<td><%#= @user.name %></td>
	</tr>
	<tr>
		<th>職業</th>
		<td><%#= @user.job %></td>
	</tr>
	<tr>
		<th>紹介文</th>
		<td><%#= @user.description %></td>
	</tr>

	<tr>
		<th>Image</th>
		<td><%#= image_tag @user.image_url %></td>
	</tr>


</table>